### ISSUE TITLE
JOSS Review: Community Guidelines / Contributing

### ISSUE THREAD

**Issue by Jammy2211** [prashjet/popkinmocks#77]
The JOSS review has the following tick box:

 Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

I may be being blinded, but I can't see anything of the sort on the project.

I would add:

1) A sentence on the main GitHub README.md on how to do this.
2) Something similar on readtheodcs.
3) A CONTRIBUTING.md file (e.g. https://github.com/Jammy2211/PyAutoLens/blob/main/CONTRIBUTING.md)

This is not a JOSS requirement, but I would also recommend adding a CODE_OF_CONDUCT.md (feel free to read and adapt this one: https://github.com/Jammy2211/PyAutoLens/blob/main/CODE_OF_CONDUCT.md)

**Comment by prashjet** [comment]
Yes, thanks for spotting this: a big oversight on my part! I took your contribution guide with a few adjustments, but searched around for a slightly shorter code of conduct.
