### ISSUE TITLE
JOSS Review (Optional): User Guide

### ISSUE THREAD

**Issue by apoudel2014** [prashjet/popkinmocks#78]
I considered leaving this as a comment, but it seems quite obvious. However, I wanted to bring it to your attention just in case it's deemed necessary to make any changes. If not, it's fine to leave it as is. It would be helpful to provide an explanation of the acronym VD (in LOSVD) when it is first introduced in the background section of the user guide, to ensure clarity for readers.

**Comment by prashjet** [comment]
Super important to define all acronyms, thanks for spotting this.
